// domains.ts: the domain separators, as field elements.
// `core/` hashes a domain string in front of every construction so a leaf can
// never be read as a node. A circuit cannot hash a string, so the same domain
// becomes one field element, derived once and pinned on both sides.

import { createHash } from "node:crypto";
import { DOMAINS, KIND_TAG, fieldFromString, type DomainName } from "@knowni/core";

/// Imported, not copied. `core/src/domains.ts` is the definition; everything
/// below is a way of writing those same strings down for a field. A second
/// copy of the list is a copy that drifts.
export { DOMAINS, type DomainName } from "@knowni/core";

/// The derivation is `core`'s, not a second copy of it: what matters here is
/// only that both sides compute the same element from the same string, and two
/// implementations of "the same" is how that stops being true.
export function domainElement(domain: string, prime: bigint): bigint {
  return fieldFromString((bytes) => Uint8Array.from(createHash("sha256").update(bytes).digest()), domain, prime);
}

/// The generated `circuits/domains.circom`, as text. CI regenerates it and
/// refuses a file that drifted, the same way it does for the signal order.
export function domainsCircom(prime: bigint): string {
  const lines = (Object.keys(DOMAINS) as DomainName[]).map((name) => {
    const value = domainElement(DOMAINS[name], prime);
    return [
      `// ${DOMAINS[name]}`,
      `function ${circomName(name)}() {`,
      `    return 0x${value.toString(16)};`,
      `}`,
    ].join("\n");
  });
  const tags = Object.entries(KIND_TAG).map(([kind, tag]) =>
    [`// claim kind: ${kind}`, `function KIND_${kind.replace(/([A-Z])/g, "_$1").toUpperCase()}() {`, `    return ${tag};`, "}"].join("\n"),
  );
  return [
    "// domains.circom: the domain separators as field elements.",
    "// GENERATED by circuits/tools/domains.ts from the strings core/ hashes.",
    "// Do not edit: CI regenerates this file and refuses one that drifted.",
    "",
    "pragma circom 2.1.6;",
    "",
    ...lines,
    "",
    "// The claim kinds, as the tags core/src/claim-fields.ts assigns them.",
    ...tags,
    "",
  ].join("\n");
}

function circomName(name: DomainName): string {
  return `DOMAIN_${name.replace(/([A-Z])/g, "_$1").toUpperCase()}`;
}
