// write-soroban-proof.ts: turns circuits/groth16/*.json (snarkjs output) into the
// byte layout Soroban's BLS12-381 host functions read, as a Rust test fixture.
// CI regenerates it and refuses one that drifted from the committed proof.
//
//   node --experimental-strip-types circuits/tools/write-soroban-proof.ts \
//     > contracts/knowni-verifier/src/real_proof.rs

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const dir = fileURLToPath(new URL("../groth16/", import.meta.url));
const read = (name: string): unknown => JSON.parse(readFileSync(`${dir}${name}`, "utf8"));

type G1 = readonly [string, string, string];
type G2 = readonly [readonly [string, string], readonly [string, string], readonly [string, string]];

interface VerificationKeyJson {
  curve: string;
  nPublic: number;
  vk_alpha_1: G1;
  vk_beta_2: G2;
  vk_gamma_2: G2;
  vk_delta_2: G2;
  IC: G1[];
}
interface ProofJson {
  pi_a: G1;
  pi_b: G2;
  pi_c: G1;
}

function be(value: string, bytes: number): string {
  const hex = BigInt(value).toString(16).padStart(bytes * 2, "0");
  if (hex.length !== bytes * 2) throw new RangeError(`${value} does not fit ${bytes} bytes`);
  return hex;
}

/// Uncompressed, big-endian, x then y: 96 bytes. snarkjs writes the
/// projective z as "1" for an affine point; anything else is not affine.
function g1(point: G1): string {
  if (point[2] !== "1") throw new Error("a G1 point is not affine");
  return be(point[0], 48) + be(point[1], 48);
}

/// 192 bytes, and the order inside each coordinate is c1 then c0: snarkjs lists
/// the Fp2 components the other way round, so copying them in order produces a
/// point that is not on the curve, not a proof that fails.
function g2(point: G2): string {
  if (point[2][0] !== "1" || point[2][1] !== "0") throw new Error("a G2 point is not affine");
  return be(point[0][1], 48) + be(point[0][0], 48) + be(point[1][1], 48) + be(point[1][0], 48);
}

function bytes(hex: string): string {
  const out: string[] = [];
  for (let i = 0; i < hex.length; i += 2) out.push(`0x${hex.slice(i, i + 2)}`);
  return `[${out.join(", ")}]`;
}

const vk = read("verification_key.json") as VerificationKeyJson;
const proof = read("proof.json") as ProofJson;
const signals = read("public.json") as string[];

if (vk.curve !== "bls12381") throw new Error(`the key is over ${vk.curve}; Stellar verifies bls12381`);
if (signals.length !== vk.nPublic || vk.IC.length !== vk.nPublic + 1) {
  throw new Error("the key, the proof and the public signals disagree on how many signals there are");
}

const lines = [
  "// real_proof.rs: a Groth16 proof over BLS12-381 produced by circuits/tools/groth16.sh,",
  "// in the byte layout Soroban reads. GENERATED by circuits/tools/write-soroban-proof.ts:",
  "// CI regenerates it and refuses one that drifted. The key is a development key.",
  "",
  `pub const ALPHA: [u8; 96] = ${bytes(g1(vk.vk_alpha_1))};`,
  `pub const BETA: [u8; 192] = ${bytes(g2(vk.vk_beta_2))};`,
  `pub const GAMMA: [u8; 192] = ${bytes(g2(vk.vk_gamma_2))};`,
  `pub const DELTA: [u8; 192] = ${bytes(g2(vk.vk_delta_2))};`,
  `pub const IC: [[u8; 96]; ${vk.IC.length}] = [`,
  ...vk.IC.map((point) => `    ${bytes(g1(point))},`),
  "];",
  `pub const A: [u8; 96] = ${bytes(g1(proof.pi_a))};`,
  `pub const B: [u8; 192] = ${bytes(g2(proof.pi_b))};`,
  `pub const C: [u8; 96] = ${bytes(g1(proof.pi_c))};`,
  `pub const SIGNALS: [[u8; 32]; ${signals.length}] = [`,
  ...signals.map((signal) => `    ${bytes(be(signal, 32))},`),
  "];",
  "",
];

process.stdout.write(lines.join("\n"));
