// write-soroban-proof.ts: the committed Groth16 key, proof and signals as a Rust
// test fixture in the byte layout Soroban reads. CI regenerates it and refuses
// one that drifted from the committed proof.
//
//   node --experimental-strip-types circuits/tools/write-soroban-proof.ts \
//     > contracts/knowni-verifier/src/real_proof.rs

import { committed } from "./soroban-encoding.ts";

function bytes(hex: string): string {
  const out: string[] = [];
  for (let i = 0; i < hex.length; i += 2) out.push(`0x${hex.slice(i, i + 2)}`);
  return `[${out.join(", ")}]`;
}

const { vk, proof, signals } = committed();

const lines = [
  "// real_proof.rs: a Groth16 proof over BLS12-381 produced by circuits/tools/groth16.sh,",
  "// in the byte layout Soroban reads. GENERATED by circuits/tools/write-soroban-proof.ts:",
  "// CI regenerates it and refuses one that drifted. The key is a development key.",
  "",
  `pub const ALPHA: [u8; 96] = ${bytes(vk.alpha)};`,
  `pub const BETA: [u8; 192] = ${bytes(vk.beta)};`,
  `pub const GAMMA: [u8; 192] = ${bytes(vk.gamma)};`,
  `pub const DELTA: [u8; 192] = ${bytes(vk.delta)};`,
  `pub const IC: [[u8; 96]; ${vk.ic.length}] = [`,
  ...vk.ic.map((point) => `    ${bytes(point)},`),
  "];",
  `pub const A: [u8; 96] = ${bytes(proof.a)};`,
  `pub const B: [u8; 192] = ${bytes(proof.b)};`,
  `pub const C: [u8; 96] = ${bytes(proof.c)};`,
  `pub const SIGNALS: [[u8; 32]; ${signals.length}] = [`,
  ...signals.map((signal) => `    ${bytes(signal)},`),
  "];",
  "",
];

process.stdout.write(lines.join("\n"));
