// write-app-fixture.ts: prints app/src/proof-fixture.ts — the example witness
// input the device-proof screen proves over. Generated from the same fixture
// the circuit tests use; CI regenerates it and refuses a file that drifted.
//
//   node --experimental-strip-types circuits/tools/write-app-fixture.ts > app/src/proof-fixture.ts

import { eligibilityFixture } from "./eligibility-fixture.ts";

const fixture = eligibilityFixture("bls12381");

process.stdout.write(
  [
    "// proof-fixture.ts: example eligibility input over BLS12-381 — invented claims,",
    "// no person behind them. GENERATED by circuits/tools/write-app-fixture.ts;",
    "// CI regenerates it and refuses one that drifted.",
    "",
    `export const PROOF_FIXTURE_INPUT: Readonly<Record<string, string | readonly string[]>> = ${JSON.stringify(fixture.input, null, 2)};`,
    "",
    "/// personhood, solvencyTier, formality, sanctions — what the proof must disclose.",
    `export const PROOF_FIXTURE_OUTPUTS = ${JSON.stringify([
      fixture.outputs.personhood,
      fixture.outputs.solvencyTier,
      fixture.outputs.formality,
      fixture.outputs.sanctions,
    ].map(String))} as const;`,
    "",
  ].join("\n"),
);
