// domains.circom: the domain separators as field elements.
// GENERATED by circuits/tools/domains.ts from the strings core/ hashes.
// Do not edit: CI regenerates this file and refuses one that drifted.

pragma circom 2.1.6;

// knowni:claim:v1
function DOMAIN_CLAIM() {
    return 0x2cb990cafe8f4048101a7b4933a7650f3d30289d601d2ec39fc15aa801845467;
}
// knowni:outcome:v1
function DOMAIN_OUTCOME() {
    return 0x2b438109be4058c0dbf014a96c630c9b464335357ee62aab71c8889af9cea64b;
}
// knowni:merkle:leaf:v1
function DOMAIN_MERKLE_LEAF() {
    return 0x246dad393cfce185259b74af3e7b4fb7426fb986aa1bc68977c7281438ee4fcb;
}
// knowni:merkle:node:v1
function DOMAIN_MERKLE_NODE() {
    return 0x16e5feb3cf4914b0be4c941052c0e2423f1ab45beec36a3f829b4eff29e62ca6;
}
// knowni:merkle:empty:v1
function DOMAIN_MERKLE_EMPTY() {
    return 0x14119a4d57c258a943c1cca1a1dbd6a4c98dc506f6b745190918232af127dd43;
}
// knowni:session:v1
function DOMAIN_SESSION() {
    return 0x4d63f695f84cd1cb36eb5ac7189fd5440177de12c937517fc0bd17529cbc99f;
}
// knowni:nullifier:v1
function DOMAIN_NULLIFIER() {
    return 0x549af6b19b175d04713b4a1255b6052daf944f02dde28eddd3f9010fd98bb46;
}
// knowni:co-sanctions:v1
function DOMAIN_SANCTIONS_LIST_SET() {
    return 0x9339c2aac83a79fb739ac7a6bb9509b69ff6ea2fbfff94a2e0db8b03d576e38;
}
// knowni:subject-ref:v1
function DOMAIN_SUBJECT_REF() {
    return 0xbddd87950bd36a7ef54a5fc0d41a42f7e46b7d36a951b21c58d92834db08d2a;
}
// knowni:snapshot:v1
function DOMAIN_SNAPSHOT() {
    return 0x2b7f26637989fb7f5459891110efe5009b3c0674781cccddd52aa43f01e7200c;
}

// The claim kinds, as the tags core/src/claim-fields.ts assigns them.
// claim kind: identity
function KIND_IDENTITY() {
    return 1;
}
// claim kind: income
function KIND_INCOME() {
    return 2;
}
// claim kind: formality
function KIND_FORMALITY() {
    return 3;
}
// claim kind: sanctions
function KIND_SANCTIONS() {
    return 4;
}
// claim kind: capacity
function KIND_CAPACITY() {
    return 5;
}
// claim kind: assetStanding
function KIND_ASSET_STANDING() {
    return 6;
}
