// domains.circom: the domain separators as field elements.
// GENERATED by circuits/tools/domains.ts from the strings core/ hashes.
// Do not edit: CI regenerates this file and refuses one that drifted.

pragma circom 2.1.6;

// knowni:claim:v1
function DOMAIN_CLAIM() {
    return 0x5d1ddf3ddfc0e071c86ac0ffb528bd6c656410e5d9d69f54e3a3503bf1845468;
}
// knowni:outcome:v1
function DOMAIN_OUTCOME() {
    return 0x4882c50f3837bbf5d1a70dc4e7453dad6b214a0bec1420603d6e6957c9cea64d;
}
// knowni:merkle:leaf:v1
function DOMAIN_MERKLE_LEAF() {
    return 0x1148a2cbd5c2a4906302281437dc286c3f19e6149d904bacff8b133d18ee4fcc;
}
// knowni:merkle:node:v1
function DOMAIN_MERKLE_NODE() {
    return 0x342542b9494077e5b4038d2bcda3135463f8c9325bf15ff44e412fbbf9e62ca8;
}
// knowni:merkle:empty:v1
function DOMAIN_MERKLE_EMPTY() {
    return 0xec8fdff0881bb4812880069b3caf59c637f194ea2bca3c90dc0e53d127dd44;
}
// knowni:session:v1
function DOMAIN_SESSION() {
    return 0x4d63f695f84cd1cb36eb5ac7189fd5440177de12c937517fc0bd17529cbc99f;
}
// knowni:nullifier:v1
function DOMAIN_NULLIFIER() {
    return 0x35adfdddfae315f9ff63fa57a6dcb8b0032d2d38a797997f212185a4ed98bb47;
}
// knowni:co-sanctions:v1
function DOMAIN_SANCTIONS_LIST_SET() {
    return 0x69fc39106ee6e7f327da37e76ebc0155ba673f33ef72da6cb5d1a3d81d576e3a;
}
// knowni:subject-ref:v1
function DOMAIN_SUBJECT_REF() {
    return 0x15f81211637a5ce82272527c8184adf69fcef937cb3795fa18f75e68fdb08d2d;
}
// knowni:snapshot:v1
function DOMAIN_SNAPSHOT() {
    return 0x5be374d65abb9ba90ca9cec792713d5dc36feebcf1d63d6f190c99d2f1e7200d;
}

// The claim kinds, as the tags core/src/claim-fields.ts assigns them.
// claim kind: identity
function KIND_IDENTITY() {
    return 1;
}
// claim kind: income
function KIND_INCOME() {
    return 2;
}
// claim kind: formality
function KIND_FORMALITY() {
    return 3;
}
// claim kind: sanctions
function KIND_SANCTIONS() {
    return 4;
}
// claim kind: capacity
function KIND_CAPACITY() {
    return 5;
}
// claim kind: assetStanding
function KIND_ASSET_STANDING() {
    return 6;
}
