// domains.circom: the domain separators as field elements.
// GENERATED by circuits/tools/domains.ts from the strings core/ hashes.
// Do not edit: CI regenerates this file and refuses one that drifted.

pragma circom 2.1.6;

// knowni:merkle:leaf:v1
function DOMAIN_MERKLE_LEAF() {
    return 0x246dad393cfce185259b74af3e7b4fb7426fb986aa1bc68977c7281438ee4fcb;
}
// knowni:merkle:node:v1
function DOMAIN_MERKLE_NODE() {
    return 0x16e5feb3cf4914b0be4c941052c0e2423f1ab45beec36a3f829b4eff29e62ca6;
}
